ifeq ($(LIBRETRO_COMM_DIR),)
	LIBRETRO_COMM_DIR = $(CORE_DIR)/libretro/libretro-common
endif

INCFLAGS   = -I$(CORE_DIR)/libretro -I$(LIBRETRO_COMM_DIR)/include -I$(CORE_DIR) -I$(CORE_DIR)/apu/ -I$(CORE_DIR)/apu/bapu

ifneq (,$(findstring msvc2003,$(platform)))
INCFLAGS += -I$(LIBRETRO_COMM_DIR)/include/compat/msvc
endif

SOURCES_C   := $(CORE_DIR)/c4emu.c \
				$(CORE_DIR)/srtc.c \
				$(CORE_DIR)/obc1.c \
				$(CORE_DIR)/spc7110.c \
				$(CORE_DIR)/fxemu.c \
				$(CORE_DIR)/sdd1.c \
				$(CORE_DIR)/seta.c \
				$(CORE_DIR)/sa1hw.c \
				$(CORE_DIR)/dsp.c \
				$(CORE_DIR)/filter/snes_ntsc.c
SOURCES_CXX := $(CORE_DIR)/apu/apu.cpp \
				 $(CORE_DIR)/apu/bapu/dsp/sdsp.cpp \
				 $(CORE_DIR)/apu/bapu/smp/smp.cpp \
				 $(CORE_DIR)/apu/bapu/smp/smp_state.cpp \
				 $(CORE_DIR)/bsx.cpp \
				 $(CORE_DIR)/cheats.cpp \
				 $(CORE_DIR)/cheats2.cpp \
				 $(CORE_DIR)/clip.cpp \
				 $(CORE_DIR)/conffile.cpp \
				 $(CORE_DIR)/controls.cpp \
				 $(CORE_DIR)/cpu.cpp \
				 $(CORE_DIR)/cpuexec.cpp \
				 $(CORE_DIR)/cpuops.cpp \
				 $(CORE_DIR)/crosshairs.cpp \
				 $(CORE_DIR)/dma.cpp \
				 $(CORE_DIR)/gfx.cpp \
				 $(CORE_DIR)/globals.cpp \
				 $(CORE_DIR)/loadzip.cpp \
				 $(CORE_DIR)/memmap.cpp \
				 $(CORE_DIR)/msu1.cpp \
				 $(CORE_DIR)/ppu.cpp \
				 $(CORE_DIR)/stream.cpp \
				 $(CORE_DIR)/sa1.cpp \
				 $(CORE_DIR)/sa1cpu.cpp \
				 $(CORE_DIR)/snapshot.cpp \
				 $(CORE_DIR)/snes9x.cpp \
				 $(CORE_DIR)/tile.cpp \
				 $(CORE_DIR)/tileimpl-n1x1.cpp \
				 $(CORE_DIR)/tileimpl-n2x1.cpp \
				 $(CORE_DIR)/tileimpl-h2x1.cpp \
				 $(CORE_DIR)/sha256.cpp \
				 $(CORE_DIR)/bml.cpp \
				 $(CORE_DIR)/movie.cpp \
				 $(CORE_DIR)/fscompat.cpp \
				 $(CORE_DIR)/libretro/libretro.cpp

ifneq (,$(findstring unix,$(platform)))
   INCFLAGS += -I$(CORE_DIR)/unzip
   SOURCES_C += $(CORE_DIR)/unzip/unzip.c \
                $(CORE_DIR)/unzip/ioapi.c
endif
ifneq (,$(findstring win,$(platform)))
   INCFLAGS += -I$(CORE_DIR)/unzip
   SOURCES_C += $(CORE_DIR)/unzip/unzip.c \
                $(CORE_DIR)/unzip/ioapi.c
endif
